// Protocol Buffer version - proto3 is the latest version

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: governance.proto

// Package name - creates a namespace for the service
// This prevents naming conflicts when multiple proto files are used

package govpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GovernanceService_SubmitForm_FullMethodName  = "/governance.GovernanceService/SubmitForm"
	GovernanceService_GetForm_FullMethodName     = "/governance.GovernanceService/GetForm"
	GovernanceService_GetAllForms_FullMethodName = "/governance.GovernanceService/GetAllForms"
	GovernanceService_DeleteForm_FullMethodName  = "/governance.GovernanceService/DeleteForm"
)

// GovernanceServiceClient is the client API for GovernanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GovernanceServiceClient interface {
	// Submit a new form submission
	// Input: FormSubmission message
	// Output: SubmissionResponse message
	SubmitForm(ctx context.Context, in *FormSubmission, opts ...grpc.CallOption) (*SubmissionResponse, error)
	// Get a form submission by ID
	// Input: GetFormRequest message (contains the ID)
	// Output: FormSubmission message (the form data)
	GetForm(ctx context.Context, in *GetFormRequest, opts ...grpc.CallOption) (*FormSubmission, error)
	// Get all form submissions
	// Input: GetAllFormsRequest message (empty for now, can add pagination later)
	// Output: GetAllFormsResponse message (list of forms)
	GetAllForms(ctx context.Context, in *GetAllFormsRequest, opts ...grpc.CallOption) (*GetAllFormsResponse, error)
	// Delete a form submission
	// Input: DeleteFormRequest message (contains the ID)
	// Output: DeleteResponse message (success/failure)
	DeleteForm(ctx context.Context, in *DeleteFormRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type governanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGovernanceServiceClient(cc grpc.ClientConnInterface) GovernanceServiceClient {
	return &governanceServiceClient{cc}
}

func (c *governanceServiceClient) SubmitForm(ctx context.Context, in *FormSubmission, opts ...grpc.CallOption) (*SubmissionResponse, error) {
	out := new(SubmissionResponse)
	err := c.cc.Invoke(ctx, GovernanceService_SubmitForm_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *governanceServiceClient) GetForm(ctx context.Context, in *GetFormRequest, opts ...grpc.CallOption) (*FormSubmission, error) {
	out := new(FormSubmission)
	err := c.cc.Invoke(ctx, GovernanceService_GetForm_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *governanceServiceClient) GetAllForms(ctx context.Context, in *GetAllFormsRequest, opts ...grpc.CallOption) (*GetAllFormsResponse, error) {
	out := new(GetAllFormsResponse)
	err := c.cc.Invoke(ctx, GovernanceService_GetAllForms_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *governanceServiceClient) DeleteForm(ctx context.Context, in *DeleteFormRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, GovernanceService_DeleteForm_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GovernanceServiceServer is the server API for GovernanceService service.
// All implementations must embed UnimplementedGovernanceServiceServer
// for forward compatibility
type GovernanceServiceServer interface {
	// Submit a new form submission
	// Input: FormSubmission message
	// Output: SubmissionResponse message
	SubmitForm(context.Context, *FormSubmission) (*SubmissionResponse, error)
	// Get a form submission by ID
	// Input: GetFormRequest message (contains the ID)
	// Output: FormSubmission message (the form data)
	GetForm(context.Context, *GetFormRequest) (*FormSubmission, error)
	// Get all form submissions
	// Input: GetAllFormsRequest message (empty for now, can add pagination later)
	// Output: GetAllFormsResponse message (list of forms)
	GetAllForms(context.Context, *GetAllFormsRequest) (*GetAllFormsResponse, error)
	// Delete a form submission
	// Input: DeleteFormRequest message (contains the ID)
	// Output: DeleteResponse message (success/failure)
	DeleteForm(context.Context, *DeleteFormRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedGovernanceServiceServer()
}

// UnimplementedGovernanceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGovernanceServiceServer struct {
}

func (UnimplementedGovernanceServiceServer) SubmitForm(context.Context, *FormSubmission) (*SubmissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitForm not implemented")
}
func (UnimplementedGovernanceServiceServer) GetForm(context.Context, *GetFormRequest) (*FormSubmission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetForm not implemented")
}
func (UnimplementedGovernanceServiceServer) GetAllForms(context.Context, *GetAllFormsRequest) (*GetAllFormsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllForms not implemented")
}
func (UnimplementedGovernanceServiceServer) DeleteForm(context.Context, *DeleteFormRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteForm not implemented")
}
func (UnimplementedGovernanceServiceServer) mustEmbedUnimplementedGovernanceServiceServer() {}

// UnsafeGovernanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GovernanceServiceServer will
// result in compilation errors.
type UnsafeGovernanceServiceServer interface {
	mustEmbedUnimplementedGovernanceServiceServer()
}

func RegisterGovernanceServiceServer(s grpc.ServiceRegistrar, srv GovernanceServiceServer) {
	s.RegisterService(&GovernanceService_ServiceDesc, srv)
}

func _GovernanceService_SubmitForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FormSubmission)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernanceServiceServer).SubmitForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GovernanceService_SubmitForm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernanceServiceServer).SubmitForm(ctx, req.(*FormSubmission))
	}
	return interceptor(ctx, in, info, handler)
}

func _GovernanceService_GetForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFormRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernanceServiceServer).GetForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GovernanceService_GetForm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernanceServiceServer).GetForm(ctx, req.(*GetFormRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GovernanceService_GetAllForms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllFormsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernanceServiceServer).GetAllForms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GovernanceService_GetAllForms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernanceServiceServer).GetAllForms(ctx, req.(*GetAllFormsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GovernanceService_DeleteForm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFormRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernanceServiceServer).DeleteForm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GovernanceService_DeleteForm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernanceServiceServer).DeleteForm(ctx, req.(*DeleteFormRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GovernanceService_ServiceDesc is the grpc.ServiceDesc for GovernanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GovernanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "governance.GovernanceService",
	HandlerType: (*GovernanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitForm",
			Handler:    _GovernanceService_SubmitForm_Handler,
		},
		{
			MethodName: "GetForm",
			Handler:    _GovernanceService_GetForm_Handler,
		},
		{
			MethodName: "GetAllForms",
			Handler:    _GovernanceService_GetAllForms_Handler,
		},
		{
			MethodName: "DeleteForm",
			Handler:    _GovernanceService_DeleteForm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "governance.proto",
}
